services:
  cms:
    image: ghcr.io/edvardsen-dev/portfolio/cms:latest
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 3021:8080
    volumes:
      - data:/pb/pb_data

volumes:
  data:
