services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADNMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 8080:8080
    volumes:
      - data:/pb/pb_data

volumes:
  data:
